name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    env:
      MODE: ${{ secrets.MODE }}
      DB_NAME: database/content.db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/test_main.py

  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: quixoticforge/pastebin
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
