name: Run Tests on Pull Request

on:
  pull_request:
    branches: [ main ]  # or change to your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./app/
    
    strategy:
      matrix:
        python-version: [3.11]


    env:
      MODE: "dev"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt

    - name: Run tests
      run: |
        pytest
